Sample Dataset

In [35]:
import pandas as pd

sensus = {
    'tinggi':[158,170,183,191,155,163,180,158,170],
    'jk':['pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita'],
    'berat':[64,86,84,80,49,59,67,54,67]
}

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67

Regression dengan KNN

features dan target

In [36]:
import numpy as np

x_train = np.array(sensus_df[['tinggi','jk']]) # features
y_train = np.array(sensus_df['berat']) # target

print("X train : ", x_train)
print("Y train : ", y_train)

X train :  [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]
Y train :  [64 86 84 80 49 59 67 54 67]


Preprocess Dataset : Konversi data ke numerik dan biner

In [37]:
x_train_transposed = np.transpose(x_train)

print("X train : ",x_train)
print("X train_transpose : ",x_train_transposed)

X train :  [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]
X train_transpose :  [[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [38]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarized = lb.fit_transform(x_train_transposed[1])

print("JK", x_train_transposed[1])
print("JK", jk_binarized.flatten())

JK ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']
JK [0 0 0 0 1 1 1 1 1]


In [39]:
jk_binarized = jk_binarized.flatten()
jk_binarized

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [40]:
x_train_transposed[1] = jk_binarized
x_train = x_train_transposed.transpose()

print("X train transpose : ",x_train_transposed[1])
print("X train : ",x_train)

X train transpose :  [0 0 0 0 1 1 1 1 1]
X train :  [[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


Training KNN Regression Model

In [41]:
from sklearn.neighbors import KNeighborsRegressor

k = 3
model = KNeighborsRegressor(n_neighbors=k)
model.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=3)

Prediksi Berat badan

In [42]:
x_new = np.array([[155, 1]])
x_new

array([[155,   1]])

In [43]:
y_pred = model.predict(x_new)
y_pred

array([55.66666667])

Evaluasi KNN Regression Model

In [44]:
x_test = np.array([[168,0],[180, 0], [160, 1],[169,1]])
y_test = np.array([65,96,52,67])

print("X test", x_test)
print("Y test", y_test)

X test [[168   0]
 [180   0]
 [160   1]
 [169   1]]
Y test [65 96 52 67]


In [45]:
y_pred = model.predict(x_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])

Coefficient of Determination atau r2

In [46]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)
print("R2 Score : ",r_squared)

R2 Score :  0.6290565226735438


Mean Absolute Error | Mean Absolute Deviation

In [47]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error Score : ",mean_absolute_error)

Mean Absolute Error Score :  8.333333333333336


Mean Squared Error | Mean Squared Deviation

In [48]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)
print("Mean Squared Error Score : ",MSE)

Mean Squared Error Score :  95.8888888888889


Permasalahan Scaling pada Features

In [49]:
from scipy.spatial.distance import euclidean

x_train = np.array([[1700, 0],[1600,1]]) # satuan milimeter
x_new = np.array([[1640,0]])

[euclidean(x_new[0],d) for d in x_train]

[60.0, 40.01249804748511]

In [50]:
x_train = np.array([[1.7,0],[1.6,1]]) # satuan meter
x_new = np.array([[1.64,0]])

[euclidean(x_new[0],d) for d in x_train]

[0.06000000000000005, 1.0007996802557442]

Standard Score

In [51]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

In [52]:
x_train = np.array([[1700,0],[1600,1]])
x_train_scaled = ss.fit_transform(x_train)
print("X Train Scaled : \n",x_train_scaled)

x_new = np.array([[1640,0]])
x_new_scaled = ss.transform(x_new)
print("X New Scaled : \n",x_new_scaled)

jarak = [euclidean(x_new_scaled[0],d) for d in x_train_scaled]
print("Jarak", jarak)

X Train Scaled : 
 [[ 1. -1.]
 [-1.  1.]]
X New Scaled : 
 [[-0.2 -1. ]]
Jarak [1.2, 2.1540659228538015]


In [53]:
x_train = np.array([[1.7,0],[1.6,1]])
x_train_scaled = ss.fit_transform(x_train)
print("X Train Scaled : \n",x_train_scaled)

x_new = np.array([[1.64,0]])
x_new_scaled = ss.transform(x_new)
print("X New Scaled : \n",x_new_scaled)

jarak = [euclidean(x_new_scaled[0],d) for d in x_train_scaled]
print("Jarak", jarak)

X Train Scaled : 
 [[ 1. -1.]
 [-1.  1.]]
X New Scaled : 
 [[-0.2 -1. ]]
Jarak [1.2000000000000026, 2.1540659228538006]


Menerapkan Features Scaling pada KNN

In [63]:
x_train = np.array([[158, 0],[170, 0],[183, 0],[191, 0],[155, 1],[163, 1],[180, 1],[158, 1],[170, 1]])
y_train = np.array([64, 86 ,84 ,80, 49, 59 ,67 ,54 ,67])

x_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65.0, 96.0, 52.0, 67.0])

Features Scaling (Standard Scaler)

In [ ]:
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

print("x train scaled", x_train_scaled)
print("x test scaled", x_test_scaled)

Training model

In [66]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

model.fit(x_train_scaled,y_train)
y_pred = model.predict(x_test_scaled)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)

print("MAE", MAE)
print("MSE", MSE)

MAE 7.583333333333336
MSE 85.13888888888893
